/**
 * Supabase database types.
 *
 * This file will be auto-generated by:
 *   npx supabase gen types typescript --project-id qpsgpfnqlbbrvawjeeaj > lib/supabase/database.types.ts
 *
 * For now, it's a placeholder with empty schema.
 * Developer-backend will regenerate this after each migration.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
